import type { V2PipelineBlueprint } from '@/lib/contracts/pipeline'

export const SITUATION_CARD_V2_PIPELINE: V2PipelineBlueprint = {
  id: 'situation-card-v2',
  label: 'Situation Card V2 pipeline',
  principle:
    'Chaque couche produit un objet verifiable avant la suivante. Le LLM referent interprete une seule fois; les couches suivantes appliquent le contrat sans reinterpreter la demande.',
  stages: [
    {
      id: 'interpretation',
      order: 1,
      label: 'Interpretation canonique',
      owner_layer: 'interpretation',
      status: 'passive',
      input_contracts: ['raw user input', 'conversation context'],
      output_contracts: ['CanonicalInterpretation'],
      latency_budget_ms: 2000,
      blocks_generation: true,
      purpose: 'Comprendre intention, domaine, situation soumise, header, angle et besoin utilisateur.',
      failure_policy: 'Si la demande est impossible a identifier, DialogueGate pose une seule clarification bloquante.',
    },
    {
      id: 'dialogue-gate',
      order: 2,
      label: 'DialogueGate',
      owner_layer: 'dialogue',
      status: 'passive',
      input_contracts: ['CanonicalInterpretation'],
      output_contracts: ['DialogueGateDecision'],
      latency_budget_ms: 80,
      blocks_generation: false,
      purpose: 'Decider entre generer, proposer une precision optionnelle ou bloquer uniquement si necessaire.',
      failure_policy: 'Par defaut, generer utilement avec prudence plutot que transformer le chat en interrogatoire.',
    },
    {
      id: 'resources',
      order: 3,
      label: 'ResourceService',
      owner_layer: 'resources',
      status: 'passive',
      input_contracts: ['CanonicalInterpretation', 'DialogueGateDecision'],
      output_contracts: ['ResourcePlan'],
      latency_budget_ms: 1200,
      blocks_generation: false,
      purpose: 'Router URL, sources rapides et enrichissements par domaine sans ralentir la SC courte.',
      failure_policy: 'Si une URL exploitable echoue, tenter recherche domaine puis signaler clairement l echec.',
    },
    {
      id: 'theatre',
      order: 4,
      label: 'Theatre reel',
      owner_layer: 'theatre',
      status: 'passive',
      input_contracts: ['CanonicalInterpretation', 'ResourcePlan'],
      output_contracts: ['ConcreteTheatre'],
      latency_budget_ms: 300,
      blocks_generation: false,
      purpose: 'Nommer acteurs, lieux, procedures, dates, preuves, contraintes et absences structurantes.',
      failure_policy: 'Si le theatre est pauvre, produire une carte prudente et rendre les manques enquetables.',
    },
    {
      id: 'expertises-metiers',
      order: 5,
      label: 'ExpertisesMetiers',
      owner_layer: 'expertisesMetiers',
      status: 'passive',
      input_contracts: ['CanonicalInterpretation', 'ConcreteTheatre'],
      output_contracts: ['ExpertisesMetiersRoute'],
      latency_budget_ms: 120,
      blocks_generation: false,
      purpose: 'Ajouter les questions expertes, preuves attendues, sources et seuils propres au domaine.',
      failure_policy: 'Si aucune expertise ne correspond, rester sur le domaine general sans inventer une specialite.',
    },
    {
      id: 'scoring',
      order: 6,
      label: 'ScoringEngine',
      owner_layer: 'scoring',
      status: 'passive',
      input_contracts: ['CanonicalInterpretation', 'ConcreteTheatre', 'ExpertisesMetiersRoute'],
      output_contracts: ['ScoringResult'],
      latency_budget_ms: 100,
      blocks_generation: false,
      purpose: 'Calculer branches Astrolabe, radar et indice d etat avec la formule canonique.',
      failure_policy: 'Fallback deterministe radar si les branches sont insuffisamment renseignees.',
    },
    {
      id: 'writing',
      order: 7,
      label: 'WritingEngine',
      owner_layer: 'writing',
      status: 'passive',
      input_contracts: ['CanonicalInterpretation', 'ConcreteTheatre', 'ScoringResult', 'ResourcePlan'],
      output_contracts: ['WritingOutput'],
      latency_budget_ms: 2500,
      blocks_generation: true,
      purpose: 'Produire SC, Lecture et Approfondir en style diamant, ancre dans le theatre reel.',
      failure_policy: 'Regenerer seulement la section ratee si QualityGate detecte hors-sol ou confusion.',
    },
    {
      id: 'quality',
      order: 8,
      label: 'QualityGate',
      owner_layer: 'quality',
      status: 'passive',
      input_contracts: ['CanonicalInterpretation', 'ConcreteTheatre', 'ScoringResult', 'WritingOutput'],
      output_contracts: ['QualityGateReport'],
      latency_budget_ms: 150,
      blocks_generation: false,
      purpose: 'Verifier fidelite, header, theatre reel, scoring, ressources, risques et phrase diamant.',
      failure_policy: 'Retourner warnings internes et corrections ciblees sans exposer la notice au public.',
    },
  ],
}

export function pipelineTotals(blueprint: V2PipelineBlueprint) {
  const total_latency_budget_ms = blueprint.stages.reduce((total, stage) => total + stage.latency_budget_ms, 0)
  const blocking_stages = blueprint.stages.filter((stage) => stage.blocks_generation).length
  const wired_stages = blueprint.stages.filter((stage) => stage.status === 'wired').length

  return {
    total_latency_budget_ms,
    blocking_stages,
    wired_stages,
    stage_count: blueprint.stages.length,
  }
}
