'use client'
// ── HomeClient ────────────────────────────────────────────────────────────────
// LOGIQUE PURE — fetch, gate, state React
// Pour modifier le design : toucher SituationCardPanel.tsx uniquement

import { useState, useEffect, useRef, useCallback } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import GlobeInteractif from '@/components/ui/globe-interactif'
import SituationCardPanel from '@/components/card/SituationCardPanel'

// ── Palette ───────────────────────────────────────────────────────────────────
const NAVY   = '#1B3A6B'
const GOLD   = '#B89A6A'
const GOLD_L = '#CCA364'
const BG     = '#F5F3EE'
const BG_P   = '#FAFAF7'
const BG_PR  = '#F7F5F0'
const TXT    = '#1a2a3a'
const TXT2   = '#5a6a7a'
const TXT3   = '#9aabb8'
const BDR    = 'rgba(26,42,58,0.1)'
const BDR_G  = 'rgba(184,154,106,0.25)'

// ── Textes ────────────────────────────────────────────────────────────────────
const TX = {
  FR: { hints: ["Un conflit d'équipe autour d'une réorganisation","Une décision stratégique avec plusieurs options","Une crise géopolitique en développement","Mon partenaire s'est éloigné — comment aborder le sujet ?","Une opportunité s'ouvre mais le timing semble mauvais"], describe:'Décrivez votre situation en texte libre.', analysing:'Analyse en cours...', waiting:'La SC apparaîtra ici', flash_title:'Flash Update', flash_sc_btn:'Situation Card complète', clarify_intro:'Pour analyser votre situation :', clarify_btn:'Analyser', partager:'Partager', restreint:'Restreint', public_lbl:'Public', historique:'Historique', saved:'Enregistrées', tagline:'Voir la structure pour pouvoir décider', signature:'Que se passe-t-il vraiment ?', offres:'Offres', connexion:'Connexion', structural_reading:'Lecture structurelle — pas une mise à jour en temps réel', generated_by:'Généré par IAAA+ SIS', on_lbl:'le' },
  EN: { hints: ["A team conflict around a restructuring","A strategic decision with multiple options","A developing geopolitical crisis","My partner has grown distant — how to approach it?","An opportunity is opening but the timing seems wrong"], describe:'Describe your situation in free text.', analysing:'Analysing...', waiting:'The SC will appear here', flash_title:'Flash Update', flash_sc_btn:'Full Situation Card', clarify_intro:'To analyse your situation:', clarify_btn:'Analyse', partager:'Share', restreint:'Private', public_lbl:'Public', historique:'History', saved:'Saved', tagline:'See the structure to decide', signature:'What is really happening?', offres:'Plans', connexion:'Sign in', structural_reading:'Structural reading — not a real-time update', generated_by:'Generated by IAAA+ SIS', on_lbl:'on' },
}

// ── Boussole ──────────────────────────────────────────────────────────────────
type CompassMode = 'idle' | 'light' | 'full' | 'off'

function Boussole({ mode, onClick, disabled }: { mode: CompassMode; onClick: () => void; disabled: boolean }) {
  const angle = useRef(0)
  const [needle, setNeedle] = useState(0)
  const raf = useRef<number | null>(null)
  useEffect(() => {
    const spinning = mode === 'full' || mode === 'light'
    if (spinning) {
      const speed = mode === 'full' ? 4 : 2
      const spin = () => { angle.current = (angle.current + speed) % 360; setNeedle(angle.current); raf.current = requestAnimationFrame(spin) }
      raf.current = requestAnimationFrame(spin)
    } else { if (raf.current) cancelAnimationFrame(raf.current); setNeedle(0) }
    return () => { if (raf.current) cancelAnimationFrame(raf.current) }
  }, [mode])
  const active = mode !== 'off' && mode !== 'idle'
  const pulse  = mode === 'idle' && !disabled
  return (
    <button onClick={onClick} disabled={disabled || mode === 'off'} title="Analyser la situation" style={{ width: 52, height: 52, borderRadius: '50%', border: 'none', background: 'none', padding: 0, cursor: disabled ? 'not-allowed' : 'pointer', filter: pulse ? 'drop-shadow(0 0 8px rgba(184,154,106,0.7))' : 'none', transition: 'filter 0.3s' }}>
      <svg width="52" height="52" viewBox="0 0 52 52">
        <circle cx="26" cy="26" r="25" fill="none" stroke={pulse || active ? GOLD : '#C8C4BC'} strokeWidth="1.5" strokeDasharray={pulse || active ? '3 2' : '2 2'} opacity={pulse || active ? 1 : 0.4} />
        <circle cx="26" cy="26" r="22" fill={pulse || active ? NAVY : '#B0BAC8'} opacity={pulse || active ? 1 : 0.5} />
        {Array.from({ length: 32 }).map((_, i) => { const a = (i * 360 / 32) * Math.PI / 180; const r1 = i % 4 === 0 ? 16 : 18; return <line key={i} x1={26 + r1 * Math.sin(a)} y1={26 - r1 * Math.cos(a)} x2={26 + 20 * Math.sin(a)} y2={26 - 20 * Math.cos(a)} stroke={GOLD} strokeWidth={i % 4 === 0 ? 1 : 0.5} opacity={pulse || active ? 0.6 : 0.2} /> })}
        <g transform={`rotate(${needle} 26 26)`}>
          <polygon points="26,9 24,26 28,26" fill="#fff" opacity={pulse || active ? 0.95 : 0.4} />
          <polygon points="26,43 24,26 28,26" fill={GOLD_L} opacity={pulse || active ? 0.9 : 0.3} />
        </g>
        <circle cx="26" cy="26" r="3" fill={pulse || active ? GOLD_L : '#9AABB8'} />
        <circle cx="26" cy="26" r="1.5" fill="#fff" />
        {pulse && <circle cx="26" cy="26" r="22" fill="none" stroke={GOLD} strokeWidth="1" opacity="0.4"><animate attributeName="r" values="22;26;22" dur="2s" repeatCount="indefinite" /><animate attributeName="opacity" values="0.4;0;0.4" dur="2s" repeatCount="indefinite" /></circle>}
      </svg>
    </button>
  )
}

// ── SidePanel ─────────────────────────────────────────────────────────────────
function SidePanel({ open, title, onClose, children }: { open: boolean; title: string; onClose: () => void; children: React.ReactNode }) {
  return (
    <>
      {open && <div onClick={onClose} style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.18)', zIndex: 200 }} />}
      <div style={{ position: 'fixed', left: 0, top: 0, bottom: 0, width: 'min(340px,90vw)', background: BG_P, borderRight: `1px solid ${BDR}`, zIndex: 201, display: 'flex', flexDirection: 'column', transform: open ? 'translateX(0)' : 'translateX(-100%)', transition: 'transform 0.26s ease', boxShadow: open ? '4px 0 20px rgba(26,42,58,0.1)' : 'none' }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 16px', borderBottom: `1px solid ${BDR}` }}>
          <span style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: 17, color: NAVY, fontWeight: 500 }}>{title}</span>
          <button onClick={onClose} style={{ background: 'none', border: 'none', cursor: 'pointer', color: TXT3, fontSize: 20 }}>×</button>
        </div>
        <div style={{ flex: 1, overflowY: 'auto', padding: '10px 16px' }}>{children}</div>
      </div>
    </>
  )
}

// ── Types ─────────────────────────────────────────────────────────────────────
type ChatMsg = { kind: 'user'; text: string } | { kind: 'flash'; etat: string; lecture: string } | { kind: 'clarify'; questions: string[] } | { kind: 'block'; reason: string }

// ── Convertit format astrolabe compact → astrolabe_scores ─────────────────────
const BRANCH_FR: Record<string, string> = { I:'Acteurs', II:'Intérêts', III:'Forces', IV:'Tensions', V:'Contraintes', VI:'Incertitude', VII:'Temps', VIII:'Espace' }
const BRANCH_EN: Record<string, string> = { I:'Actors', II:'Interests', III:'Forces', IV:'Tensions', V:'Constraints', VI:'Uncertainty', VII:'Time', VIII:'Space' }

function getStateLabel(v: number, lang: 'FR' | 'EN'): string {
  if (lang === 'EN') { if (v < 40) return 'Clear'; if (v < 55) return 'Navigable'; if (v < 70) return 'Watch'; if (v < 90) return 'Critical'; return 'Loss of Control' }
  if (v < 40) return 'Stable'; if (v < 55) return 'Contrôlable'; if (v < 70) return 'Vigilance'; if (v < 90) return 'Critique'; return 'Hors contrôle'
}

function convertAstrolabe(data: { state?: number; branches?: Array<{b:string;s:number;p:boolean}> }, lang: 'FR' | 'EN') {
  if (!data?.branches) return null
  const state = data.state ?? 50
  return {
    state_index_final: state,
    state_label: getStateLabel(state, 'FR'),
    state_label_en: getStateLabel(state, 'EN'),
    astrolabe_scores: data.branches.map(br => ({ branch: br.b, display_score: br.s, is_primary: br.p, name: BRANCH_FR[br.b] ?? br.b, name_en: BRANCH_EN[br.b] ?? br.b, label: '', label_en: '' }))
  }
}

// ── COMPOSANT PRINCIPAL ───────────────────────────────────────────────────────
export default function HomeClient() {
  const [lang, setLang]             = useState<'FR' | 'EN'>('FR')
  const [situation, setSituation]   = useState('')
  const [chatMsgs, setChatMsgs]     = useState<ChatMsg[]>([])
  const [answers, setAnswers]       = useState<string[]>([])
  const [scData, setScData]         = useState<Record<string, any> | null>(null)
  const [scLoading, setScLoading]   = useState(false)
  const [scExpanded, setScExpanded] = useState(false)
  const [compassMode, setCompassMode] = useState<CompassMode>('idle')
  const [panelHistory, setPanelHistory] = useState(false)
 const [parchemin, setParchemin] = useState<'idle'|'unrolling'|'done'>('idle')
  const chatEndRef = useRef<HTMLDivElement>(null)

  const t = TX[lang]
  const hasText = situation.trim().length > 8
  const lastMsg = chatMsgs[chatMsgs.length - 1]
  const waitingForAnswers = lastMsg?.kind === 'clarify'
  const isBlocked = lastMsg?.kind === 'block'
  const compassDisabled = !hasText || scLoading || isBlocked || (waitingForAnswers && answers.every(a => !a.trim()))

  useEffect(() => { chatEndRef.current?.scrollIntoView({ behavior: 'smooth' }) }, [chatMsgs])

  const handleGenerate = useCallback(async () => {
    if (compassDisabled) return
    const text = situation.trim()
    let fullText = text
    if (waitingForAnswers && lastMsg?.kind === 'clarify') {
      const qa = lastMsg.questions.map((q, i) => answers[i]?.trim() ? `${q}\n${answers[i]}` : '').filter(Boolean).join('\n\n')
      if (qa) fullText = `${text}\n\nPrécisions :\n${qa}`
    }
    setScLoading(true); setCompassMode('full')
    setChatMsgs(prev => [...prev, { kind: 'user', text }])
    setSituation('')
    try {
      const gateRes = await fetch('/api/generate', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ situation: fullText, lang: lang.toLowerCase() }) })
      const gateData = await gateRes.json()
      if (gateData.gate === 'FLASH') {
        setCompassMode('idle')
        const fl = gateData.flash
        setChatMsgs(prev => [...prev, { kind: 'flash', etat: lang === 'FR' ? fl.etat_actuel : (fl.etat_actuel_en ?? fl.etat_actuel), lecture: lang === 'FR' ? fl.lecture : (fl.lecture_en ?? fl.lecture) }])
        setScData(null); setScLoading(false); return
      }
      if (gateData.gate === 'CLARIFY') {
        setCompassMode('idle')
        setChatMsgs(prev => [...prev, { kind: 'clarify', questions: gateData.questions ?? [] }])
        setAnswers(new Array(gateData.questions?.length ?? 0).fill(''))
        setScData(null); setScLoading(false); return
      }
      if (gateData.gate === 'BLOCK') {
        setCompassMode('off')
        setChatMsgs(prev => [...prev, { kind: 'block', reason: gateData.reason ?? '' }])
        setScData(null); setScLoading(false); return
      }
      // GENERATE — parallèle, astrolabe affiché en premier
      const astroPromise = fetch('/api/astrolabe', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ situation: fullText }) })
      const scPromise    = fetch('/api/generate',   { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ situation: fullText, lang: lang.toLowerCase(), mode: 'generate_full' }) })
      const astroData = await (await astroPromise).json()
      const partial = convertAstrolabe(astroData, lang)
    if (partial) {
  setScData(partial)
  setCompassMode('light')
  setParchemin('unrolling')
  setTimeout(() => setParchemin('done'), 800)
}
      const scData2 = await (await scPromise).json()
      if (scData2.sc) { setScData({ ...(partial ?? {}), ...scData2.sc }) }
      setCompassMode('idle'); setScLoading(false)
    } catch (e) { console.error(e); setCompassMode('idle'); setScLoading(false) }
  }, [situation, lang, compassDisabled, waitingForAnswers, lastMsg, answers])

  async function handleFlashExpand(text: string) {
    setScLoading(true); setCompassMode('full')
    try {
      const astroPromise = fetch('/api/astrolabe', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ situation: text }) })
      const scPromise    = fetch('/api/generate',   { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ situation: text, mode: 'generate_full', lang: lang.toLowerCase() }) })
      const astroData = await (await astroPromise).json()
      const partial = convertAstrolabe(astroData, lang)
      if (partial) { setScData(partial); setCompassMode('light') }
      const scData2 = await (await scPromise).json()
      if (scData2.sc) { setScData({ ...(partial ?? {}), ...scData2.sc }) }
    } catch (e) { console.error(e) }
    finally { setScLoading(false); setCompassMode('idle') }
  }

  const MODULES = [
    { tag: 'Clarity', sub: { FR: 'Individuel', EN: 'Individual' }, href: '/clarity' },
    { tag: 'SIS',     sub: { FR: 'Collectif Pro', EN: 'Pro Collective' }, href: '/sis' },
    { tag: 'IAAA+',   sub: { FR: 'Gouvernance', EN: 'Governance' }, href: '/enterprise' },
    { tag: 'ATLAS',   sub: { FR: 'Cartes publiques', EN: 'Public cards' }, href: '/library' },
  ]
  const HISTORY_ITEMS = [
    { title: 'Séquestration — ONG RDC', index: 85 },
    { title: 'Guerre Iran — Jour 19',   index: 91 },
    { title: "Conflit d'équipe",         index: 54 },
  ]

  return (
    <>
      <SidePanel open={panelHistory} title={t.historique} onClose={() => setPanelHistory(false)}>
        {HISTORY_ITEMS.map((item, i) => (
          <div key={i} style={{ padding: '9px 0', borderBottom: `1px solid ${BDR}`, cursor: 'pointer' }}>
            <div style={{ fontSize: 13, color: TXT, fontStyle: 'italic', marginBottom: 3 }}>{item.title}</div>
            <span style={{ fontSize: 10, color: GOLD }}>Index {item.index}</span>
          </div>
        ))}
      </SidePanel>
      <SidePanel open={panelSaved} title={t.saved} onClose={() => setPanelSaved(false)}>
        <div style={{ fontSize: 11, color: TXT3, padding: '16px 0' }}>{lang === 'FR' ? 'Aucune carte enregistrée.' : 'No saved cards yet.'}</div>
      </SidePanel>

      {scExpanded && scData && (
        <div style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.55)', zIndex: 300, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 20 }}>
          <div style={{ background: BG_P, borderRadius: 12, width: '100%', maxWidth: 760, maxHeight: '92vh', display: 'flex', flexDirection: 'column', border: `1px solid ${BDR_G}` }}>
            <SituationCardPanel sc={scData} lang={lang} onExpand={() => setScExpanded(false)} />
          </div>
        </div>
      )}

      <div style={{ minHeight: '100vh', background: BG }}>
        {/* HEADER */}
        <header style={{ display: 'grid', gridTemplateColumns: '1fr auto 1fr', alignItems: 'center', padding: '16px 36px', background: BG, borderBottom: `1px solid ${BDR}`, position: 'sticky', top: 0, zIndex: 100 }}>
          <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 10, textDecoration: 'none' }}>
            <div style={{ width: 46, height: 46, borderRadius: '50%', overflow: 'hidden', border: `1px solid ${BDR_G}` }}>
              <Image src="/pictos/LOOGO IAAA+.jpg" alt="IAAA+" width={46} height={46} style={{ objectFit: 'cover', width: '100%', height: '100%' }} unoptimized />
            </div>
            <div>
              <div style={{ fontSize: 14, fontWeight: 500, color: NAVY, fontFamily: "'Cinzel',serif", letterSpacing: '.02em' }}>Situation Card</div>
              <div style={{ fontSize: 10, color: TXT3 }}>powered by IAAA+</div>
            </div>
          </Link>
          <div style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: 22, fontWeight: 600, color: GOLD, textAlign: 'center', fontStyle: 'italic' }}>
            {lang === 'FR' ? <>Comprendre les situations complexes<br />par une carte.</> : <>Understanding complex situations<br />through a card.</>}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'flex-end', gap: 20 }}>
            <Link href="/pricing" style={{ fontSize: 12.5, color: TXT2, textDecoration: 'none' }}>{t.offres}</Link>
            <Link href="/login"   style={{ fontSize: 12.5, color: TXT2, textDecoration: 'none' }}>{t.connexion}</Link>
            <div style={{ display: 'flex', gap: 6, paddingLeft: 12, borderLeft: `1px solid ${BDR}` }}>
              {(['FR','EN'] as const).map(l => <button key={l} onClick={() => setLang(l)} style={{ fontSize: 12, fontWeight: 500, cursor: 'pointer', border: 'none', background: 'none', color: lang === l ? NAVY : TXT2 }}>{l}</button>)}
            </div>
          </div>
        </header>

        {/* WORKSPACE */}
        <main style={{ maxWidth: 1160, margin: '0 auto', padding: '24px 28px 0' }}>
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16, minHeight: 480 }}>

            {/* BLOC GAUCHE */}
            <div style={{ background: BG_P, border: `1px solid ${BDR}`, borderRadius: 16, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
              <div style={{ display: 'flex', borderBottom: `1px solid ${BDR}`, padding: '0 16px', gap: 2 }}>
                {[lang === 'FR' ? 'Texte' : 'Text', 'Documents', 'Images'].map((tb, i) => (
                  <button key={tb} style={{ padding: '10px 9px', fontSize: 12, color: i === 0 ? TXT2 : TXT3, cursor: 'pointer', border: 'none', background: 'none', borderBottom: i === 0 ? `2px solid ${GOLD_L}` : '2px solid transparent' }}>{tb}</button>
                ))}
              </div>
              {chatMsgs.length > 0 && (
                <div style={{ padding: '12px 16px', display: 'flex', flexDirection: 'column', gap: 10, maxHeight: 220, overflowY: 'auto' }}>
                  {chatMsgs.map((msg, i) => {
                    if (msg.kind === 'user') return <div key={i} style={{ alignSelf: 'flex-end', background: NAVY, color: '#fff', borderRadius: '10px 10px 2px 10px', padding: '7px 12px', fontSize: 12, maxWidth: '80%', fontStyle: 'italic' }}>{msg.text}</div>
                    if (msg.kind === 'flash') return (
                      <div key={i} style={{ alignSelf: 'flex-start', background: 'rgba(184,154,106,0.08)', border: `1px solid ${BDR_G}`, borderRadius: '2px 10px 10px 10px', padding: '10px 12px', maxWidth: '90%' }}>
                        <div style={{ fontSize: 8, color: GOLD, letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 6 }}>{t.flash_title}</div>
                        <div style={{ fontSize: 11, color: TXT, marginBottom: 3 }}><span style={{ color: TXT3, fontSize: 9 }}>État actuel — </span>{msg.etat}</div>
                        <div style={{ fontSize: 11, color: TXT2, fontStyle: 'italic', marginBottom: 8 }}><span style={{ color: TXT3, fontSize: 9 }}>Lecture — </span>{msg.lecture}</div>
                        <div style={{ fontSize: 8, color: TXT3, marginBottom: 8 }}>{t.structural_reading}</div>
                        <button onClick={() => handleFlashExpand(chatMsgs.find(m => m.kind === 'user')?.text ?? situation)} style={{ background: NAVY, color: '#fff', border: 'none', borderRadius: 6, padding: '5px 12px', fontSize: 10, fontFamily: "'Cinzel',serif", letterSpacing: '.06em', cursor: 'pointer' }}>{t.flash_sc_btn}</button>
                      </div>
                    )
                    if (msg.kind === 'clarify') return (
                      <div key={i} style={{ alignSelf: 'flex-start', background: BG_P, border: `1px solid ${BDR}`, borderRadius: '2px 10px 10px 10px', padding: '10px 12px', maxWidth: '95%', width: '95%' }}>
                        <div style={{ fontSize: 11, color: TXT2, fontStyle: 'italic', marginBottom: 8 }}>{t.clarify_intro}</div>
                        {msg.questions.map((q, qi) => (
                          <div key={qi} style={{ marginBottom: 8 }}>
                            <div style={{ fontSize: 11, color: TXT, marginBottom: 3 }}>{q}</div>
                            <textarea value={answers[qi] ?? ''} onChange={e => { const a = [...answers]; a[qi] = e.target.value; setAnswers(a) }} rows={2} style={{ width: '100%', border: `1px solid ${BDR}`, borderRadius: 5, padding: '5px 7px', fontSize: 11, fontFamily: "'DM Sans',sans-serif", resize: 'none', background: BG, color: TXT, outline: 'none' }} />
                          </div>
                        ))}
                      </div>
                    )
                    if (msg.kind === 'block') return <div key={i} style={{ alignSelf: 'flex-start', background: 'rgba(224,107,74,0.06)', border: '1px solid rgba(224,107,74,0.25)', borderRadius: '2px 10px 10px 10px', padding: '8px 12px', maxWidth: '90%', fontSize: 11, color: '#A32D2D' }}>{msg.reason}</div>
                    return null
                  })}
                  <div ref={chatEndRef} />
                </div>
              )}
              <div style={{ flex: 1, position: 'relative', padding: '0 16px' }}>
                <textarea value={situation} onChange={e => setSituation(e.target.value)} style={{ width: '100%', height: '100%', minHeight: chatMsgs.length > 0 ? 120 : 260, border: 'none', background: 'transparent', resize: 'none', fontFamily: "'DM Sans',sans-serif", fontSize: 14, color: TXT, outline: 'none', lineHeight: 1.7, paddingTop: 12 }} />
                {!situation && chatMsgs.length === 0 && (
                  <div style={{ position: 'absolute', top: 12, left: 16, right: 16, pointerEvents: 'none' }}>
                    <span style={{ fontSize: 14, color: TXT3, display: 'block', marginBottom: 10 }}>{t.describe}</span>
                    {t.hints.map((h, i) => <span key={i} onClick={() => setSituation(h)} style={{ display: 'block', fontSize: 12.5, color: TXT3, opacity: i === 3 ? 0.38 : 0.55, marginBottom: 5, fontStyle: i === 3 ? 'italic' : 'normal', pointerEvents: 'auto', cursor: 'pointer' }}>{h}</span>)}
                  </div>
                )}
              </div>
              <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '8px 16px 12px', borderTop: `1px solid ${BDR}` }}>
                <div style={{ display: 'flex', gap: 8 }}>
                  <button style={{ width: 30, height: 30, border: 'none', background: 'none', cursor: 'pointer', color: TXT2, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="15 3 21 3 21 9" /><polyline points="9 21 3 21 3 15" /><line x1="21" y1="3" x2="14" y2="10" /><line x1="3" y1="21" x2="10" y2="14" /></svg>
                  </button>
                  <button style={{ width: 30, height: 30, border: `1px solid ${BDR}`, background: BG_P, cursor: 'pointer', borderRadius: '50%', color: TXT2, display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><rect x="9" y="2" width="6" height="11" rx="3" /><path d="M19 10a7 7 0 01-14 0" /><line x1="12" y1="19" x2="12" y2="22" /></svg>
                  </button>
                </div>
                <Boussole mode={compassMode} onClick={handleGenerate} disabled={compassDisabled} />
              </div>
            </div>

            {/* BLOC DROIT */}
            <div style={{ background: BG_PR, border: `1px solid ${BDR_G}`, borderRadius: 16, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '10px 14px', borderBottom: `1px solid ${BDR_G}` }}>
                {[t.restreint, t.public_lbl].map(l => <button key={l} style={{ padding: '5px 11px', borderRadius: 7, fontSize: 12, fontWeight: 500, cursor: 'pointer', border: '1px solid #dde3e8', color: '#b0bcc8', background: 'transparent' }}>{l}</button>)}
                <button style={{ width: 24, height: 24, borderRadius: '50%', border: `1px solid ${BDR}`, background: 'none', cursor: 'pointer', fontSize: 11, color: TXT3, marginRight: 'auto' }}>?</button>
                <div style={{ display: 'flex', gap: 3 }}>
                  {(['FR','EN'] as const).map(l => <button key={l} onClick={() => setLang(l)} style={{ fontSize: 10, fontWeight: 500, padding: '3px 7px', border: `1px solid ${l === lang ? GOLD : BDR}`, borderRadius: 5, background: l === lang ? `${GOLD}22` : 'transparent', color: l === lang ? GOLD : TXT3, cursor: 'pointer' }}>{l}</button>)}
                </div>
                <button style={{ display: 'flex', alignItems: 'center', gap: 5, padding: '5px 12px', borderRadius: 7, background: NAVY, color: 'white', border: 'none', fontSize: 12, fontWeight: 500, cursor: 'pointer' }}>
                  <svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M4 12v8a2 2 0 002 2h12a2 2 0 002-2v-8" /><polyline points="16 6 12 2 8 6" /><line x1="12" y1="2" x2="12" y2="15" /></svg>
                  {t.partager}
                </button>
              </div>
              {scLoading && !scData ? (
                <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 16 }}>
                  <GlobeInteractif size={200} />
                  <div style={{ fontSize: 12, color: TXT3, fontStyle: 'italic', fontFamily: "'Cormorant Garamond',serif" }}>{t.analysing}</div>
                </div>
              ) : scData ? (
                <div style={{ flex: 1, overflow: 'hidden' }}>
                  <SituationCardPanel sc={scData} lang={lang} onExpand={() => setScExpanded(true)} />
                </div>
              ) : (
                <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: 16 }}>
                  <GlobeInteractif size={240} />
                  <div style={{ fontSize: 11, color: TXT3, fontStyle: 'italic', marginTop: 14, fontFamily: "'Cormorant Garamond',serif" }}>{t.waiting}</div>
                  <div style={{ display: 'flex', gap: 8, marginTop: 10 }}>
                    {[{ c: '#1D9E75', l: lang === 'FR' ? 'Stabilisation' : 'Stabilization' }, { c: '#E06B4A', l: lang === 'FR' ? 'Escalade' : 'Escalation' }, { c: '#378ADD', l: lang === 'FR' ? 'Rupture' : 'Regime Shift' }].map(tr => (
                      <div key={tr.l} style={{ display: 'flex', alignItems: 'center', gap: 3, fontSize: 9, color: TXT3 }}>
                        <div style={{ width: 6, height: 6, borderRadius: '50%', background: tr.c }} />{tr.l}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>

          {/* SOUS-BARRE */}
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8, padding: '16px 0 14px' }}>
            <div style={{ display: 'flex', gap: 24, alignItems: 'center' }}>
              <button onClick={() => setPanelHistory(true)} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, background: 'none', border: 'none', cursor: 'pointer' }}>
                <div style={{ width: 40, height: 40, borderRadius: '50%', overflow: 'hidden', border: `1px solid ${BDR}` }}>
                  <Image src="/pictos/horloge.jpg" alt="" width={40} height={40} style={{ objectFit: 'cover', width: '100%', height: '100%' }} unoptimized />
                </div>
                <span style={{ fontSize: 9, color: TXT3 }}>{t.historique}</span>
              </button>
              <button onClick={() => setPanelSaved(true)} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 4, background: 'none', border: 'none', cursor: 'pointer' }}>
                <div style={{ width: 40, height: 40, borderRadius: '50%', overflow: 'hidden', border: `1px solid ${BDR}` }}>
                  <Image src="/pictos/Enregistrer_nobg.jpg" alt="" width={40} height={40} style={{ objectFit: 'cover', width: '100%', height: '100%' }} unoptimized />
                </div>
                <span style={{ fontSize: 9, color: TXT3 }}>{t.saved}</span>
              </button>
            </div>
            <div style={{ fontFamily: "'Cormorant Garamond',serif", fontSize: 22, fontStyle: 'italic', color: GOLD_L }}>{t.signature}</div>
            <div style={{ fontSize: 12, color: TXT3 }}>{t.tagline}</div>
          </div>
        </main>

        {/* MODULES */}
        <section style={{ background: '#EFEDE7', padding: '20px 28px', borderTop: `1px solid ${BDR}` }}>
          <div style={{ maxWidth: 1160, margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: 12 }}>
            {MODULES.map(m => (
              <Link key={m.tag} href={m.href} style={{ textDecoration: 'none' }}>
                <div style={{ background: BG_P, border: `1px solid ${BDR}`, borderRadius: 10, padding: '14px' }}>
                  <div style={{ fontFamily: "'Cinzel',serif", fontSize: 13, fontWeight: 500, color: NAVY, marginBottom: 3 }}>{m.tag}</div>
                  <div style={{ fontSize: 11, color: TXT3, marginBottom: 8 }}>{m.sub[lang]}</div>
                  <div style={{ fontSize: 11, color: TXT3 }}>→</div>
                </div>
              </Link>
            ))}
          </div>
        </section>

        {/* FOOTER */}
        <footer style={{ background: BG_P, borderTop: `1px solid ${BDR}`, padding: '12px 36px' }}>
          <div style={{ maxWidth: 1160, margin: '0 auto', display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 10 }}>
            <Link href="/" style={{ display: 'flex', alignItems: 'center', gap: 8, textDecoration: 'none' }}>
              <div style={{ width: 32, height: 32, borderRadius: '50%', overflow: 'hidden', border: `1px solid ${BDR_G}` }}>
                <Image src="/pictos/LOOGO IAAA+.jpg" alt="IAAA+" width={32} height={32} style={{ objectFit: 'cover', width: '100%', height: '100%' }} unoptimized />
              </div>
              <span style={{ fontFamily: "'Cinzel',serif", fontSize: 11, color: TXT3 }}>situationcard.com</span>
            </Link>
            <div style={{ display: 'flex', gap: 18, flexWrap: 'wrap' }}>
              {[{ l: lang === 'FR' ? 'À propos' : 'About', h: '/about' }, { l: 'Contact', h: '/contact' }, { l: lang === 'FR' ? 'Confidentialité' : 'Privacy', h: '/privacy' }, { l: lang === 'FR' ? 'Conditions' : 'Terms', h: '/terms' }, { l: lang === 'FR' ? 'Mentions légales' : 'Legal', h: '/legal' }].map(item => <Link key={item.l} href={item.h} style={{ fontSize: 11, color: TXT3, textDecoration: 'none' }}>{item.l}</Link>)}
            </div>
          </div>
        </footer>
      </div>
    </>
  )
}
