/**
 * IAAA · /terms
 * Conditions d'utilisation — version minimale staging.
 */

import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Terms of Use — Situation Card',
}

const SECTIONS = [
  {
    title: 'What Situation Card is',
    content: `Situation Card is a structured analysis tool. It helps you think through complex situations by generating a Situation Card — a structured reading of forces, tensions, vulnerabilities and trajectories.

A Situation Card is not a decision. It is not advice. It is not a prediction. It is an instrument of clarity, not a substitute for your own judgment.

The decision always remains yours.`,
  },
  {
    title: 'What you can use it for',
    content: `You can use Situation Card for personal, professional, organisational, or research purposes.

You can share public cards freely — they are published under a Creative Commons Attribution licence (CC BY 4.0). This means anyone can read, share, and build on public cards, provided they attribute the source.

Private cards belong to you and are visible only to you.`,
  },
  {
    title: 'What you are responsible for',
    content: `You are responsible for the situations you submit. Do not submit:

— Personal information about third parties without their consent.
— Content that is illegal, defamatory, or intended to harm.
— Sensitive information that you are not authorised to share.

The AI system generates a structured reading of what you submit. The quality of the output depends on the quality and honesty of the input.`,
  },
  {
    title: 'Limitations of the service',
    content: `Situation Card works with the information you provide and publicly available knowledge. It does not have access to classified information, private intelligence, or confidential data.

On human situations: the analysis is always partial. The person or organisation described may not be fully represented by the submitted description. The card is a structured entry point, not a complete picture.

On geopolitical situations: the analysis is based on public information only. It does not reflect intelligence assessments or classified sources.

Do not use Situation Card as the sole basis for medical, legal, financial, or safety-critical decisions.`,
  },
  {
    title: 'Your account',
    content: `You are responsible for maintaining the security of your account credentials. Notify us immediately if you suspect unauthorised access.

You may delete your account at any time. Your data will be permanently deleted within 30 days of account deletion.`,
  },
  {
    title: 'Our responsibilities',
    content: `We provide the platform as is. We work to maintain availability and quality, but we do not guarantee uninterrupted access.

We do not guarantee the accuracy, completeness, or appropriateness of any Situation Card generated by the system. The AI system can make errors, omissions, or produce outputs that do not apply to your specific situation.`,
  },
  {
    title: 'Changes to these terms',
    content: `We may update these terms. If changes materially affect your rights, we will notify you by email at least 14 days before the changes take effect. Continued use of the platform after notification constitutes acceptance.`,
  },
  {
    title: 'Contact',
    content: `For any question about these terms: legal@situationcard.com

These terms were last updated on 28 March 2026.`,
  },
]

export default function TermsPage() {
  return (
    <main style={{
      background: '#F5F0E8',
      minHeight: '100vh',
      fontFamily: 'var(--font-dm-sans, system-ui, sans-serif)',
      color: '#1A2E5A',
    }}>
      <nav style={{ background: '#fff', borderBottom: '1px solid #E8E0D0', padding: '14px 28px', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
        <Link href="/" style={{ fontFamily: 'var(--font-cinzel, serif)', fontSize: '13px', color: '#1A2E5A', textDecoration: 'none', letterSpacing: '0.1em' }}>
          SITUATION CARD
        </Link>
        <Link href="/" style={{ fontSize: '12px', color: '#9A8860', textDecoration: 'none' }}>← Back</Link>
      </nav>

      <div style={{ maxWidth: '680px', margin: '0 auto', padding: '60px 28px' }}>

        <p style={{ fontFamily: 'var(--font-cinzel, serif)', fontSize: '10px', color: '#9A8860', letterSpacing: '0.2em', textTransform: 'uppercase', marginBottom: '16px' }}>
          Legal
        </p>
        <h1 style={{ fontFamily: 'var(--font-cormorant, serif)', fontSize: 'clamp(1.6rem, 3.5vw, 2.2rem)', fontWeight: 400, color: '#1A2E5A', marginBottom: '8px' }}>
          Terms of Use
        </h1>
        <p style={{ fontSize: '12px', color: '#9A8860', marginBottom: '48px' }}>
          Last updated: 28 March 2026
        </p>

        {SECTIONS.map((section) => (
          <div key={section.title} style={{ marginBottom: '36px' }}>
            <h2 style={{ fontSize: '14px', fontWeight: 600, color: '#1A2E5A', marginBottom: '10px' }}>
              {section.title}
            </h2>
            <div style={{ fontSize: '14px', color: '#5A6A7A', lineHeight: 1.8, whiteSpace: 'pre-line' }}>
              {section.content}
            </div>
            <div style={{ height: '1px', background: '#E8E0D0', marginTop: '28px' }} />
          </div>
        ))}

      </div>
    </main>
  )
}
