export type OfferType = 'clarity' | 'sis' | 'iaaa+'

export type MetierProfile = {
  id: string
  label: string
  keywords: string[]
  offer: OfferType | OfferType[]
  usecases: string[]
  signal: string
  patterns: string[]
}

export const METIER_PROFILES: MetierProfile[] = [
  {
    id: 'medecin_urgentiste',
    label: 'Médecin urgentiste',
    keywords: ['urgentiste', 'urgences', 'triage', 'réanimation', 'smur'],
    offer: 'sis',
    usecases: [
      'triage multifacteurs',
      "tensions d'équipe",
      'décision de fin de vie',
    ],
    signal: "Qui porte l'information critique sans pouvoir la remonter ?",
    patterns: [
      'Emotional Load Asymmetry',
      'Role Container Failure',
      'Coordination failure',
    ],
  },
  {
    id: 'medecin_generaliste',
    label: 'Médecin généraliste',
    keywords: ['généraliste', 'medecin traitant', 'cabinet médical', 'patient complexe'],
    offer: 'clarity',
    usecases: [
      'patient complexe médico-social',
      'annonce diagnostique',
      'tension avec spécialiste',
    ],
    signal: 'Ce que le patient ne dit pas mais que la situation révèle',
    patterns: [
      'Unspoken Contract Breakdown',
      'Boundary Erosion',
      'Care Burden Imbalance',
    ],
  },
  {
    id: 'psychologue_therapeute',
    label: 'Psychologue/Thérapeute',
    keywords: ['psychologue', 'thérapeute', 'therapeute', 'thérapie', 'thérapeutique'],
    offer: 'clarity',
    usecases: [
      'blocage professionnel',
      'situation relationnelle complexe',
      'transition de vie',
    ],
    signal: 'Ce que la personne évite de regarder directement',
    patterns: [
      'Dependency Loop',
      'Shame-Avoidance Loop',
      'Attachment-Security Conflict',
      'Deferred Conflict Saturation',
    ],
  },
  {
    id: 'healthtech',
    label: 'Healthtech',
    keywords: ['healthtech', 'hôpital', 'hopital', 'déploiement hospitalier', 'medtech'],
    offer: 'sis',
    usecases: [
      'déploiement hospitalier',
      'pivot avant levée',
      'relation partenariale tendue',
    ],
    signal: "Le décideur réel dans l'hôpital n'est souvent pas celui qui signe",
    patterns: [
      'Power asymmetry',
      'Principal-agent conflict',
      'Strategic lag',
    ],
  },
  {
    id: 'avocat',
    label: 'Avocat',
    keywords: ['avocat', 'plaidoirie', 'm&a', 'divorce conflictuel', 'contentieux'],
    offer: 'sis',
    usecases: [
      'dossier complexe avant plaidoirie',
      'négociation M&A',
      'divorce conflictuel',
    ],
    signal: "La contradiction que la partie adverse n'a pas encore vue",
    patterns: [
      'Power asymmetry',
      'Strategic lag',
      'Coordination failure',
    ],
  },
  {
    id: 'juge_magistrat',
    label: 'Juge/Magistrat',
    keywords: ['juge', 'magistrat', 'cour', 'tribunal', 'instruction'],
    offer: 'iaaa+',
    usecases: [
      'dossier multi-parties',
      "tensions entre expertises contradictoires",
    ],
    signal: "L'acteur dont le comportement détermine l'issue sans être jugé",
    patterns: [
      'Institutional absorption limit',
      'Power asymmetry',
    ],
  },
  {
    id: 'journaliste_investigation',
    label: 'Journaliste investigation',
    keywords: ['journaliste', 'investigation', 'enquête', 'enquete', 'publication'],
    offer: 'sis',
    usecases: [
      'dossier multisources avant publication',
      'dynamique sous-jacente au-delà des faits',
    ],
    signal: "Le signal faible que les grandes agences n'ont pas encore intégré",
    patterns: [
      'Escalation spiral',
      'Strategic lag',
      'Dependency trap',
    ],
  },
  {
    id: 'drh',
    label: 'DRH',
    keywords: ['drh', 'ressources humaines', 'plan social', 'réorganisation', 'reorganisation'],
    offer: 'sis',
    usecases: [
      "conflit d'équipe structurel",
      'réorganisation difficile',
      'tensions avant plan social',
    ],
    signal: "Le manager que tout le monde contourne et dont personne ne parle",
    patterns: [
      'Role Container Failure',
      'Coordination failure',
      'Institutional absorption limit',
    ],
  },
  {
    id: 'manager',
    label: 'Manager',
    keywords: ['manager', 'équipe', 'equipe', 'lead', 'responsable'],
    offer: 'sis',
    usecases: [
      'équipe sous pression chronique',
      'décision avec acteurs aux intérêts divergents',
    ],
    signal: "Qui dans l'équipe porte ce que tout le monde voit mais personne ne dit",
    patterns: [
      'Emotional Load Asymmetry',
      'Dependency Loop',
      'Deferred Conflict Saturation',
    ],
  },
  {
    id: 'syndicaliste',
    label: 'Syndicaliste',
    keywords: ['syndicat', 'syndicaliste', 'grève', 'greve', 'négociation sociale'],
    offer: 'sis',
    usecases: [
      'négociation sociale',
      'conflit collectif avant grève',
    ],
    signal: "Le salarié que la DRH surveille et que le syndicat protège sans comprendre pourquoi",
    patterns: [
      'Power asymmetry',
      'Coordination failure',
      'Hidden Resentment Accumulation',
    ],
  },
  {
    id: 'entrepreneur',
    label: 'Entrepreneur',
    keywords: ['entrepreneur', 'fondateur', 'fondatrice', 'associés', 'associes', 'levée', 'levee'],
    offer: 'sis',
    usecases: [
      'crise avec associés',
      'décision stratégique sous incertitude',
      'relation VC tendue',
    ],
    signal: 'La décision que tout le monde reporte parce qu’elle implique de choisir entre deux alliances',
    patterns: [
      'Loyalty Conflict',
      'Fear-of-Loss Paralysis',
      'Dependency trap',
    ],
  },
  {
    id: 'vc_investisseur',
    label: 'VC/Investisseur',
    keywords: [
      'vc',
      'venture capital',
      'capital-risque',
      'investisseur',
      'investisseurs',
      'investissement startup',
      'startup investing',
      'dealflow',
      'deal flow',
      'due diligence',
      'term sheet',
      'pre-seed',
      'seed',
      'série a',
      'serie a',
      'follow-on',
      'board',
      'portfolio',
      'traction',
      'runway',
    ],
    offer: 'sis',
    usecases: [
      'sélection de startups',
      'analyse de dossier avant investissement',
      'décision de follow-on',
      'tension entre fondateurs',
      'portfolio company en difficulté',
    ],
    signal: "Le décalage entre la promesse pitchée, la preuve d'usage et le risque d'exécution",
    patterns: [
      'Principal-agent conflict',
      'Strategic lag',
      'Power asymmetry',
      'Selection under uncertainty',
    ],
  },
  {
    id: 'dirigeant_pme',
    label: 'Dirigeant PME',
    keywords: ['pme', 'dirigeant', 'transmission', 'gouvernance familiale'],
    offer: 'sis',
    usecases: [
      'transmission difficile',
      'conflit familial dans la gouvernance',
      'décision stratégique seul',
    ],
    signal: 'La personne clé dont le départ mettrait tout en danger — et que personne ne protège',
    patterns: [
      'Recognition Asymmetry',
      'Role Container Failure',
      'Dependency Loop',
    ],
  },
  {
    id: 'financier_banquier',
    label: 'Financier/Banquier',
    keywords: ['banquier', 'financier', 'crédit', 'credit', 'investissement'],
    offer: 'sis',
    usecases: [
      'dossier crédit complexe',
      'dossier investissement complexe',
      'tension avec client corporate',
    ],
    signal: "Ce que le bilan ne dit pas sur la dynamique réelle de l'entreprise",
    patterns: [
      'Strategic lag',
      'Principal-agent conflict',
      'Power asymmetry',
    ],
  },
  {
    id: 'auditeur_compliance',
    label: 'Auditeur/Compliance',
    keywords: ['auditeur', 'compliance', 'conformité', 'conformite', 'non-conformité'],
    offer: 'sis',
    usecases: [
      'non-conformité complexe',
      'risques systémiques organisationnels',
    ],
    signal: 'Le processus que tout le monde contourne et dont personne ne parle',
    patterns: [
      'Institutional absorption limit',
      'Principal-agent conflict',
      'Invisible Standards Pressure',
    ],
  },
  {
    id: 'elu',
    label: 'Élu',
    keywords: ['élu', 'elu', 'majorité', 'majorite', 'aménagement', 'amenagement'],
    offer: 'iaaa+',
    usecases: [
      "décision d'aménagement sensible",
      'crise institutionnelle',
    ],
    signal: 'Ce que les élus de la majorité disent en privé et ne diront jamais en séance',
    patterns: [
      'Coordination failure',
      'Power asymmetry',
      'Strategic lag',
      'Institutional absorption limit',
    ],
  },
  {
    id: 'directeur_cabinet',
    label: 'Directeur de cabinet',
    keywords: ['directeur de cabinet', 'cabinet ministériel', 'cabinet ministeriel', 'inter-ministérielle'],
    offer: 'iaaa+',
    usecases: [
      'administration en réforme',
      'tension inter-ministérielle',
      'crise institutionnelle discrète',
    ],
    signal: "La décision qui n'est officiellement jamais prise mais qui détermine tout",
    patterns: [
      'Institutional absorption limit',
      'Principal-agent conflict',
      'Power asymmetry',
    ],
  },
  {
    id: 'diplomate',
    label: 'Diplomate',
    keywords: ['diplomate', 'bilatérale', 'bilaterale', 'note de position', 'étatique'],
    offer: 'iaaa+',
    usecases: [
      'tension bilatérale',
      'crise diplomatique avant note de position',
      "lecture d'un interlocuteur étatique",
    ],
    signal: 'Ce que la partie adverse ne peut pas dire en public mais communique autrement',
    patterns: [
      'Power asymmetry',
      'Strategic lag',
      'Coordination failure',
    ],
  },
  {
    id: 'militaire_stratege',
    label: 'Militaire/Stratège',
    keywords: ['militaire', 'stratège', 'stratege', 'déploiement', 'deploiement', 'opérationnelle'],
    offer: 'iaaa+',
    usecases: [
      'situation opérationnelle avant déploiement',
      'géopolitique en développement',
      'tension interne sous pression',
    ],
    signal: "La variable que les modèles classiques n'intègrent pas",
    patterns: [
      'Escalation spiral',
      'Strategic lag',
      'Coordination failure',
    ],
  },
  {
    id: 'coordinateur_ong_terrain',
    label: 'Coordinateur ONG terrain',
    keywords: ['ong', 'humanitaire', 'terrain', 'accès humanitaire', 'fraude paiement'],
    offer: 'sis',
    usecases: [
      'situation sécuritaire avant déploiement',
      'accès humanitaire négocié',
      'fraude sur paiement',
    ],
    signal: "L'acteur local qui facilite et qui peut basculer",
    patterns: [
      'Power asymmetry',
      'Dependency trap',
      'Trust breakdown',
    ],
  },
  {
    id: 'association_ess',
    label: 'Association/ESS',
    keywords: ['association', 'ess', 'bénévoles', 'benevoles', 'gouvernance collective'],
    offer: 'clarity',
    usecases: [
      'tension interne entre bénévoles et salariés',
      'décision de gouvernance collective difficile',
    ],
    signal: "Le cofondateur dont le départ serait catastrophique mais dont on ne parle pas",
    patterns: [
      'Role Container Failure',
      'Loyalty Conflict',
      'Unspoken Contract Breakdown',
    ],
  },
  {
    id: 'travailleur_social',
    label: 'Travailleur social',
    keywords: ['travailleur social', 'signalement', 'famille en crise', 'enfant'],
    offer: 'clarity',
    usecases: [
      'situation de famille en crise',
      'décision de signalement',
    ],
    signal: "Ce que l'enfant montre et que les adultes n'arrivent pas à nommer",
    patterns: [
      'Boundary Erosion',
      'Care Burden Imbalance',
      'Coordination failure',
    ],
  },
  {
    id: 'consultant',
    label: 'Consultant',
    keywords: ['consultant', 'mission', 'client', 'sponsor', 'résistance interne'],
    offer: 'sis',
    usecases: [
      'mission avec client en résistance interne',
      'diagnostic contradictoire avec décideur',
    ],
    signal: 'Le sponsor qui dit oui en réunion et bloque en dehors',
    patterns: [
      'Principal-agent conflict',
      'Power asymmetry',
      'Validation Trap',
    ],
  },
  {
    id: 'coach',
    label: 'Coach',
    keywords: ['coach', 'transition', 'blocage professionnel', 'tranchage'],
    offer: 'clarity',
    usecases: [
      'blocage professionnel répété',
      'moment de transition difficile',
      'décision importante avant tranchage',
    ],
    signal: "Ce que la personne sait mais n'arrive pas encore à formuler",
    patterns: [
      'Fear-of-Loss Paralysis',
      'Attachment-Security Conflict',
      'Identity Split',
      'Deferred Conflict Saturation',
    ],
  },
  {
    id: 'analyste_geopolitique',
    label: 'Analyste géopolitique',
    keywords: ['géopolitique', 'geopolitique', 'note analytique', 'acteur étatique', 'acteur etatique'],
    offer: ['sis', 'iaaa+'],
    usecases: [
      'situation internationale en développement',
      'note analytique',
      "lecture d'un acteur étatique",
    ],
    signal: "Le signal faible que les grandes agences n'ont pas encore intégré",
    patterns: [
      'Escalation spiral',
      'Strategic lag',
      'Dependency trap',
    ],
  },
  {
    id: 'enseignant_formateur',
    label: 'Enseignant/Formateur',
    keywords: ['enseignant', 'formateur', 'classe difficile', 'parent', 'administration'],
    offer: 'clarity',
    usecases: [
      'classe difficile',
      'relation tendue avec administration ou parent',
      'décision de reconversion',
    ],
    signal: "L'élève que tout le groupe surveille sans le dire",
    patterns: [
      'Boundary Erosion',
      'Invisible Standards Pressure',
      'Emotional Load Asymmetry',
    ],
  },
  {
    id: 'chercheur_academique',
    label: 'Chercheur/Académique',
    keywords: ['chercheur', 'académique', 'academique', 'laboratoire', 'publication'],
    offer: ['clarity', 'sis'],
    usecases: [
      'conflit dans un laboratoire',
      'décision de publication sensible',
      'collaboration sensible',
    ],
    signal: 'La collaboration que tout le monde sait compromise mais que personne ne nomme',
    patterns: [
      'Power asymmetry',
      'Recognition Asymmetry',
      'Invisible Standards Pressure',
    ],
  },
  {
    id: 'architecte_urbaniste',
    label: 'Architecte/Urbaniste',
    keywords: ['architecte', 'urbaniste', 'maître d’ouvrage', 'maitre d’ouvrage', 'opposition locale'],
    offer: 'sis',
    usecases: [
      'projet en opposition locale',
      "tensions entre maître d'ouvrage, maître d'œuvre et usagers",
    ],
    signal: "L'usage réel du lieu que personne n'a prévu dans le programme",
    patterns: [
      'Coordination failure',
      'Unspoken Contract Breakdown',
      'Power asymmetry',
    ],
  },
  {
    id: 'communicant_rp',
    label: 'Communicant/RP',
    keywords: ['communication', 'rp', 'réputation', 'reputation', 'journalistes'],
    offer: 'sis',
    usecases: [
      'crise de réputation avant prise de parole',
      'tensions entre communication interne et externe',
    ],
    signal: "Ce que les journalistes savent déjà et qu'on n'a pas encore dit",
    patterns: [
      'Shame-Avoidance Loop',
      'Strategic lag',
      'Trust breakdown',
    ],
  },
]
