import type { ExpertiseMetierPlaybook, SituationDomainV2 } from '../contracts'

const DEFAULT_PLAYBOOK: ExpertiseMetierPlaybook = {
  id: 'general',
  domain: 'general',
  label_fr: 'General',
  typical_actors: ['acteurs directs', 'acteurs influents', 'acteurs capables de bloquer'],
  typical_institutions: [],
  procedures_or_rules: ['regles explicites', 'regles implicites', 'precedents'],
  expected_evidence: ['fait observable', 'chronologie', 'source ou document'],
  common_blind_spots: ['acteur absent', 'contrainte cachee', 'preuve manquante'],
  source_channels: ['official', 'news_agency', 'other'],
  probability_markers: ['etabli par source', 'probable par faisceau d indices', 'hypothese a tester'],
  tipping_points: ['decision observable', 'blocage', 'changement de role'],
  writing_anchors: ['nommer qui agit', 'nommer ce qui manque', 'nommer le seuil'],
}

export const DOMAIN_PLAYBOOKS: Partial<Record<SituationDomainV2, ExpertiseMetierPlaybook>> = {
  institutional_crisis: {
    id: 'institutional_crisis',
    domain: 'institutional_crisis',
    label_fr: 'Crise institutionnelle',
    typical_actors: [
      'dirigeant ou candidat nomme',
      'parti politique',
      'responsables electoraux locaux',
      'gouverneurs',
      'juges',
      'medias allies',
      'relais militants',
    ],
    typical_institutions: [
      'Etats federes',
      'autorites electorales',
      'Congres',
      'tribunaux',
      'Cour supreme',
      'secretaires d Etat locaux',
    ],
    procedures_or_rules: [
      'certification des resultats',
      'recours judiciaires',
      'contentieux electoral',
      'calendrier electoral',
      'refus de certification',
    ],
    expected_evidence: [
      'decision publique',
      'document procedural',
      'declaration officielle',
      'precedent historique',
      'consigne de parti',
      'recours depose',
    ],
    common_blind_spots: [
      'relais institutionnel',
      'regle exploitable',
      'acteur capable de bloquer',
      'precedent du 6 janvier 2021',
      'pression sur les responsables electoraux',
    ],
    source_channels: ['official', 'legal', 'news_agency', 'local_media'],
    probability_markers: ['recours prepares', 'refus de certification', 'alignement parti-institution'],
    tipping_points: ['une contestation devient procedure', 'un arbitre institutionnel valide le blocage'],
    writing_anchors: ['ne pas confondre contestation et capacite institutionnelle'],
  },
  startup_market: {
    id: 'startup_market',
    domain: 'startup_market',
    label_fr: 'Startup et marche',
    typical_actors: ['fondateurs', 'clients', 'investisseurs', 'partenaires', 'regulateurs'],
    typical_institutions: ['registre legal', 'incubateur', 'autorite de regulation'],
    procedures_or_rules: ['tarification', 'contrat client', 'cadre fiscal et social', 'propriete intellectuelle'],
    expected_evidence: ['usage repete', 'client identifiable', 'revenu', 'pricing', 'partenariat'],
    common_blind_spots: ['droit du travail', 'volonte de payer', 'dependance plateforme', 'cout cache'],
    source_channels: ['company', 'market', 'technical', 'social_public'],
    probability_markers: ['preuve client', 'traction', 'retention', 'jobs ouverts'],
    tipping_points: ['un segment paye', 'un partenaire credible engage', 'la contrainte legale bloque'],
    writing_anchors: ['separer promesse, cible, usage et preuve'],
  },
  family: {
    id: 'family',
    domain: 'family',
    label_fr: 'Lien familial',
    typical_actors: ['personne qui parle', 'personne qui se tait', 'tiers familial', 'personne qui porte la charge'],
    typical_institutions: [],
    procedures_or_rules: ['role implicite', 'limite posee', 'conversation de reprise'],
    expected_evidence: ['message exact', 'geste observable', 'rythme', 'changement de comportement'],
    common_blind_spots: ['honte', 'peur de decevoir', 'projection', 'attente non dite', 'fatigue'],
    source_channels: ['other'],
    probability_markers: ['coherence entre signe et acte', 'repetition', 'disponibilite reelle'],
    tipping_points: ['un silence devient retrait durable', 'une parole claire retablit le lien'],
    writing_anchors: ['ne pas remplacer l ambiguite par un recit'],
  },
  health_body: {
    id: 'health_body',
    domain: 'health_body',
    label_fr: 'Sante',
    typical_actors: ['patient', 'medecin', 'pharmacien', 'urgentiste'],
    typical_institutions: ['autorite sanitaire', 'hopital', 'cabinet medical'],
    procedures_or_rules: ['signes d alerte', 'consultation', 'urgence', 'suivi medical'],
    expected_evidence: ['symptomes', 'duree', 'intensite', 'antecedents', 'source medicale'],
    common_blind_spots: ['urgence sous-estimee', 'automedication', 'interaction medicamenteuse'],
    source_channels: ['health_authority', 'research', 'official'],
    probability_markers: ['symptome persistant', 'signe d alerte', 'avis professionnel'],
    tipping_points: ['danger immediat', 'symptome qui s aggrave', 'besoin d examen'],
    writing_anchors: ['structurer sans diagnostiquer'],
  },
  science_research: {
    id: 'science_research',
    domain: 'science_research',
    label_fr: 'Sciences',
    typical_actors: ['chercheurs', 'laboratoires', 'pairs', 'institutions scientifiques'],
    typical_institutions: ['universite', 'revue scientifique', 'agence de recherche'],
    procedures_or_rules: ['protocole', 'publication', 'revue par les pairs', 'reproductibilite'],
    expected_evidence: ['article', 'methode', 'donnees', 'replication', 'consensus'],
    common_blind_spots: ['biais de publication', 'correlation causalite', 'taille echantillon'],
    source_channels: ['research', 'official', 'technical'],
    probability_markers: ['meta-analyse', 'replication', 'preprint non relu'],
    tipping_points: ['resultat reproduit', 'retractation', 'consensus qui change'],
    writing_anchors: ['separer hypothese, preuve, methode et consensus'],
  },
}

export function getDomainPlaybook(domain: SituationDomainV2): ExpertiseMetierPlaybook {
  return DOMAIN_PLAYBOOKS[domain] ?? {
    ...DEFAULT_PLAYBOOK,
    domain,
  }
}
