'use client'

/**
 * IAAA · LecturePanel
 *
 * Displays the deep causal explanation of a situation.
 * Ephemeral — shown on /generate only, never persisted.
 *
 * Lecture ≠ summary of SC.
 * Lecture = internal logic that explains WHY the SC looks the way it does.
 *
 * Structure generated by the AI (in system prompt):
 *   1. Core logic
 *   2. Foundational sequence
 *   3. Reinforcing loop
 *   4. Key tension
 *   5. Synthesis formula
 *
 * UI: triggered by "Lectures" button next to "Partager" in SC header zone.
 * Closes on click outside or on button toggle.
 */

import { BookOpen, X } from 'lucide-react'

interface Props {
  lecture:  string
  onClose?: () => void
}

export default function LecturePanel({ lecture, onClose }: Props) {
  return (
    <div
      style={{
        background:   '#FEFCF6',
        border:       '1px solid var(--border-gold)',
        borderRadius: '2px',
        padding:      '20px 22px',
        position:     'relative',
      }}
    >
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
        <BookOpen
          size={18}
          strokeWidth={1.5}
          color='var(--navy)'
        />
        <p style={{
          fontFamily:    'var(--font-cinzel)',
          fontSize:      '0.72rem',
          letterSpacing: '0.14em',
          textTransform: 'uppercase',
          color:         'var(--navy)',
          fontWeight:    500,
        }}>
          Lecture
        </p>
        <p style={{
          fontFamily: 'var(--font-dm-sans)',
          fontSize:   '0.65rem',
          color:      'var(--text-muted)',
          marginLeft: '4px',
          fontStyle:  'italic',
        }}>
          — logique interne de la situation
        </p>

        {onClose && (
          <button
            onClick={onClose}
            style={{
              marginLeft:  'auto',
              background:  'none',
              border:      'none',
              cursor:      'pointer',
              color:       'var(--text-muted)',
              padding:     '2px',
              display:     'flex',
              alignItems:  'center',
            }}
            aria-label="Fermer la lecture"
          >
            <X size={14} strokeWidth={1.5} />
          </button>
        )}
      </div>

      {/* Divider */}
      <div style={{ height: '0.5px', background: 'var(--border-gold-subtle)', marginBottom: '16px' }} />

      {/* Content */}
      <div
        style={{
          fontFamily:  'var(--font-dm-sans)',
          fontSize:    '0.80rem',
          color:       'var(--text-primary)',
          fontWeight:  300,
          lineHeight:  1.75,
          whiteSpace:  'pre-wrap',
        }}
      >
        {lecture}
      </div>

      {/* Footer note */}
      <div style={{
        marginTop:    '16px',
        paddingTop:   '12px',
        borderTop:    '0.5px solid var(--border-gold-subtle)',
        display:      'flex',
        alignItems:   'center',
        gap:          '6px',
      }}>
        <BookOpen size={11} strokeWidth={1.5} color='var(--text-muted)' />
        <p style={{
          fontFamily:    'var(--font-cinzel)',
          fontSize:      '0.55rem',
          color:         'var(--text-muted)',
          letterSpacing: '0.1em',
          textTransform: 'uppercase',
          opacity:       0.6,
        }}>
          Éclairage — ne remplace pas le jugement
        </p>
      </div>
    </div>
  )
}
