'use client'
// ── SituationCardPanel ────────────────────────────────────────────────────────
// DESIGN ONLY — ne contient aucune logique de fetch ou de state global
// Pour modifier l'ordre des sections, les couleurs, les labels : toucher UNIQUEMENT ce fichier

import { useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'

// ── Palette ───────────────────────────────────────────────────────────────────
const NAVY   = '#1B3A6B'
const GOLD   = '#B89A6A'
const BG_P   = '#FAFAF7'
const TXT    = '#1a2a3a'
const TXT2   = '#5a6a7a'
const TXT3   = '#9aabb8'
const BDR    = 'rgba(26,42,58,0.1)'
const BDR_G  = 'rgba(184,154,106,0.25)'

// ── Textes SC ─────────────────────────────────────────────────────────────────
const TX_SC = {
  FR: { tab_situation:'Situation', tab_cap:'Cap', tab_analyse:'Analyse', partager:'Partager', lectures:'Lectures', collaboration:'Collaboration', generated_by:'Généré par IAAA+ SIS', on_lbl:'le', tracabilite:'TRACABILITÉ', lecture_label:'LECTURE', vulnerability_label:'VULNÉRABILITÉ PRINCIPALE', asymmetry_label:'ASYMÉTRIE', mouvements_label:'MOUVEMENTS', situation_soumise:'SITUATION SOUMISE' },
  EN: { tab_situation:'Situation', tab_cap:'Cap', tab_analyse:'Analysis', partager:'Share', lectures:'Readings', collaboration:'Collaborate', generated_by:'Generated by IAAA+ SIS', on_lbl:'on', tracabilite:'TRACEABILITY', lecture_label:'READING', vulnerability_label:'MAIN VULNERABILITY', asymmetry_label:'ASYMMETRY', mouvements_label:'RECOMMENDED ACTIONS', situation_soumise:'SUBMITTED SITUATION' },
}

// ── AstrolabeRadial — design figé ─────────────────────────────────────────────
function AstrolabeRadial({ scores }: { scores: Array<{ display_score: number; name: string; branch: string }> }) {
  const cx = 120, cy = 120
  const RINGS = [32, 62, 92]
  const LABEL_R = 125
  const FILLS   = ['#B8D4F0', '#F0CA70', '#E87C7C']
  const STROKES = ['#7AAEDC', '#D4A830', '#C84040']
  const EMPTY = '#E0DCD4', EMPTY_S = '#C8C4BC'
  return (
    <svg viewBox="0 0 240 240" width="210" height="210" style={{ overflow: 'visible' }}>
      <circle cx={cx} cy={cy} r={108} fill="none" stroke="#C8B880" strokeWidth="1.2" />
      {Array.from({ length: 32 }).map((_, t) => {
        const ta = (t * 360 / 32 - 90) * Math.PI / 180
        const isMaj = t % 4 === 0
        return <line key={t} x1={cx + 100 * Math.cos(ta)} y1={cy + 100 * Math.sin(ta)} x2={cx + (isMaj ? 94 : 97) * Math.cos(ta)} y2={cy + (isMaj ? 94 : 97) * Math.sin(ta)} stroke="#C8B880" strokeWidth={isMaj ? 1 : 0.5} />
      })}
      {RINGS.map(r => <circle key={r} cx={cx} cy={cy} r={r} fill="none" stroke="#DDD8CC" strokeWidth="0.6" strokeDasharray="3 3" />)}
      {scores.map((s, i) => {
        const a = (i * 45 - 90) * Math.PI / 180
        const perpA = a + Math.PI / 2
        const lx = cx + LABEL_R * Math.cos(a), ly = cy + LABEL_R * Math.sin(a)
        const dotColor = s.display_score === 3 ? '#801050' : s.display_score === 2 ? '#888000' : '#004858'
        return (
          <g key={i}>
            <line x1={cx} y1={cy} x2={cx + 95 * Math.cos(a)} y2={cy + 95 * Math.sin(a)} stroke="#E0DCD4" strokeWidth="0.8" />
            {RINGS.map((r, lvl) => {
              const px = cx + r * Math.cos(a), py = cy + r * Math.sin(a)
              const hl = r * 0.28, hw = r * 0.12
              const filled = s.display_score >= (lvl + 1)
              const t1x = px + hl * Math.cos(a), t1y = py + hl * Math.sin(a)
              const t2x = px - hl * Math.cos(a), t2y = py - hl * Math.sin(a)
              const s1x = px + hw * Math.cos(perpA), s1y = py + hw * Math.sin(perpA)
              const s2x = px - hw * Math.cos(perpA), s2y = py - hw * Math.sin(perpA)
              return <polygon key={lvl} points={`${t1x},${t1y} ${s1x},${s1y} ${t2x},${t2y} ${s2x},${s2y}`} fill={filled ? FILLS[lvl] : EMPTY} stroke={filled ? STROKES[lvl] : EMPTY_S} strokeWidth={filled ? '1' : '0.5'} strokeLinejoin="miter" opacity={filled ? 0.92 : 0.5} />
            })}
            <circle cx={lx} cy={ly} r="11" fill="#F8F3E8" stroke="#C8B880" strokeWidth="0.9" />
            <circle cx={lx} cy={ly - 5} r="2" fill={dotColor} opacity="0.85" />
            <text x={lx} y={ly + 3.5} textAnchor="middle" dominantBaseline="middle" fontSize="8" fontFamily="'Cinzel',Georgia,serif" fill="#6A5A38">{s.branch}</text>
          </g>
        )
      })}
      <circle cx={cx} cy={cy} r="7" fill="#D4BC78" stroke="#A89050" strokeWidth="1" />
      <circle cx={cx} cy={cy} r="3" fill="#8A6830" />
      {[{ c: '#B8D4F0', l: 'Calme' }, { c: '#F0CA70', l: 'Modéré' }, { c: '#E87C7C', l: 'Agité' }].map((item, i) => (
        <g key={i} transform={`translate(${28 + i * 64}, 228)`}>
          <polygon points="8,0 4,8 8,16 12,8" fill={item.c} stroke="none" opacity="0.9" />
          <text x="18" y="11" fontSize="8" fill={TXT3} fontFamily="'Cinzel',Georgia,serif">{item.l}</text>
        </g>
      ))}
    </svg>
  )
}

// ── ForceLines ────────────────────────────────────────────────────────────────
const BRANCH_DESC_FR: Record<string, string> = { I:'Ceux qui agissent, influencent ou bloquent.', II:'Ce que les parties cherchent, défendent ou refusent.', III:'Ce qui pousse, soutient ou accélère la situation.', IV:'Ce qui oppose, fragilise ou met sous pression.', V:"Ce qui limite l'action et réduit les marges.", VI:'Ce qui reste flou, instable ou difficile à vérifier.', VII:"Les rythmes, délais et fenêtres d'action.", VIII:'Les lieux, distances, frontières et zones de contact.' }
const BRANCH_DESC_EN: Record<string, string> = { I:'Those who act, influence or block.', II:'What each party seeks, defends or refuses.', III:'What pushes, sustains or accelerates the situation.', IV:'What opposes, weakens or puts under pressure.', V:'What limits action and reduces room to manoeuvre.', VI:'What remains unclear, unstable or hard to verify.', VII:'The rhythms, deadlines and windows for action.', VIII:'The places, distances, borders and contact zones.' }
const FL_COLORS = ['#E0DCD4', '#B8D4F0', '#F0CA70', '#E87C7C']

function ForceLines({ scores, lang }: { scores: Array<{ display_score: number; name: string; name_en: string; branch: string }>; lang: 'FR' | 'EN' }) {
  return (
    <div style={{ width: '100%' }}>
      {scores.map((s, i) => {
        const desc = lang === 'FR' ? BRANCH_DESC_FR[s.branch] : BRANCH_DESC_EN[s.branch]
        return (
          <div key={i} style={{ marginBottom: 8 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 2 }}>
              <span style={{ fontSize: 9, color: TXT3, fontStyle: 'italic', width: 22, textAlign: 'right', flexShrink: 0 }}>{s.branch}</span>
              <span style={{ fontSize: 10, color: TXT2, width: 72, flexShrink: 0, fontWeight: 500 }}>{lang === 'FR' ? s.name : s.name_en}</span>
              <div style={{ flex: 1, height: 5, background: '#EDEAE4', borderRadius: 3, overflow: 'hidden' }}>
                <div style={{ width: `${(s.display_score / 3) * 100}%`, height: '100%', background: FL_COLORS[s.display_score] ?? FL_COLORS[0], borderRadius: 3, transition: 'width 0.5s ease' }} />
              </div>
            </div>
            {desc && <div style={{ paddingLeft: 30, fontSize: 9, color: TXT3, fontStyle: 'italic', lineHeight: 1.4 }}>{desc}</div>}
          </div>
        )
      })}
    </div>
  )
}

// ── SituationCardPanel ────────────────────────────────────────────────────────
export default function SituationCardPanel({ sc, lang, onExpand }: {
  sc: Record<string, any>; lang: 'FR' | 'EN'; onExpand: () => void
}) {
  const [tab, setTab] = useState<'situation' | 'cap' | 'analyse'>('situation')
  const [lecturesOpen, setLecturesOpen] = useState(false)
  const t = TX_SC[lang]

  const g = (fr: string, en: string) => {
    const frVal = sc[fr] ?? sc[fr.replace('_fr', '')] ?? ''
    const enVal = sc[en] ?? sc[en.replace('_en', '')] ?? frVal
    return lang === 'FR' ? frVal : enVal
  }

  const insight       = g('insight_fr',            'insight_en')
  const vulnerability = g('main_vulnerability_fr', 'main_vulnerability_en')
  const asymmetry     = g('asymmetry_fr',          'asymmetry_en')
  const signal        = g('key_signal_fr',          'key_signal_en')
  const submitted     = g('submitted_situation_fr', 'submitted_situation_en')
  const stateLabel    = g('state_label',            'state_label_en')
  const cap           = sc.cap_summary ?? sc.cap ?? {}
  const hook          = lang === 'FR' ? (cap.hook_fr ?? cap.hook ?? '') : (cap.hook_en ?? cap.hook ?? '')
  const capInsight    = lang === 'FR' ? (cap.insight_fr ?? cap.insight ?? '') : (cap.insight_en ?? cap.insight ?? '')
  const watch         = lang === 'FR' ? (cap.watch_fr ?? cap.watch ?? '') : (cap.watch_en ?? cap.watch ?? '')
  const trajectories  = sc.trajectories ?? []
  const avertissement = lang === 'FR' ? (sc.avertissement_fr ?? sc.analysis?.avertissement ?? '') : (sc.avertissement_en ?? sc.analysis?.avertissement_en ?? sc.avertissement_fr ?? '')
  const lectureSysteme = lang === 'FR'
    ? (sc.lecture_systeme_fr ?? sc.analysis?.lecture_systeme ?? '')
    : (sc.lecture_systeme_en ?? sc.analysis?.lecture_systeme_en ?? sc.lecture_systeme_fr ?? '')

  const mouvements    = lang === 'FR' ? (sc.movements_fr ?? sc.analysis?.mouvements_recommandes ?? []) : (sc.movements_en ?? sc.analysis?.mouvements_recommandes_en ?? sc.movements_fr ?? sc.analysis?.mouvements_recommandes ?? [])

  const TABS = [
    { key: 'situation' as const, label: t.tab_situation },
    { key: 'cap'       as const, label: t.tab_cap },
    { key: 'analyse'   as const, label: t.tab_analyse },
  ]

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%', overflow: 'hidden', position: 'relative' }}>

      {/* Panel Lectures */}
      {lecturesOpen && (
        <>
          <div onClick={() => setLecturesOpen(false)} style={{ position: 'absolute', inset: 0, background: 'rgba(0,0,0,0.18)', zIndex: 50 }} />
          <div style={{ position: 'absolute', right: 0, top: 0, bottom: 0, width: 'min(360px,90%)', background: '#FEFCF6', borderLeft: `1px solid ${BDR_G}`, zIndex: 51, display: 'flex', flexDirection: 'column', boxShadow: '-4px 0 20px rgba(26,42,58,0.1)' }}>
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px 16px', borderBottom: `1px solid ${BDR_G}` }}>
              <div>
                <div style={{ fontSize: 8, color: GOLD, letterSpacing: '.12em', fontFamily: "'Cinzel',serif", marginBottom: 2 }}>LECTURE STRUCTURELLE</div>
                <div style={{ fontSize: 11, color: TXT3, fontStyle: 'italic' }}>logique interne de la situation</div>
              </div>
              <button onClick={() => setLecturesOpen(false)} style={{ background: 'none', border: 'none', cursor: 'pointer', color: TXT3, fontSize: 20 }}>×</button>
            </div>
            <div style={{ flex: 1, overflowY: 'auto', padding: '16px' }}>
              {lectureSysteme ? (
                <div style={{ fontSize: 13, color: TXT, fontFamily: "'Cormorant Garamond',serif", lineHeight: 1.9, fontStyle: 'italic' }}>
                  {lectureSysteme}
                </div>
              ) : (
                <div style={{ fontSize: 11, color: TXT3, fontStyle: 'italic' }}>
                  {lang === 'FR' ? 'Lecture non disponible pour cette carte.' : 'Reading not available for this card.'}
                </div>
              )}
            </div>
          </div>
        </>
      )}

      {/* Header SC */}
      <div style={{ padding: '10px 14px 8px', background: `linear-gradient(to right, ${NAVY}, #2A4A80)`, display: 'flex', alignItems: 'center', gap: 8 }}>
        <Link href="/" style={{ display: 'flex', alignItems: 'center', flexShrink: 0, textDecoration: 'none' }}>
          <div style={{ width: 26, height: 26, borderRadius: '50%', overflow: 'hidden', border: '1px solid rgba(200,168,64,0.4)' }}>
            <Image src="/pictos/LOOGO IAAA+.jpg" alt="IAAA+" width={26} height={26} style={{ objectFit: 'cover', width: '100%', height: '100%' }} unoptimized />
          </div>
        </Link>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{ fontSize: 8, color: 'rgba(255,255,255,0.45)', letterSpacing: '.12em', fontFamily: "'Cinzel',serif", marginBottom: 2 }}>POWERED BY IAAA+ · SITUATION CARD</div>
          <div style={{ fontSize: 13, color: '#fff', fontStyle: 'italic', fontFamily: "'Cormorant Garamond',serif", lineHeight: 1.3 }}>{g('title_fr', 'title_en')}</div>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 6, flexShrink: 0 }}>
          <div style={{ background: 'rgba(255,255,255,0.12)', border: '1px solid rgba(200,168,64,0.5)', borderRadius: 20, padding: '3px 10px', display: 'flex', alignItems: 'center', gap: 5 }}>
            <span style={{ fontSize: 14, fontWeight: 700, color: '#E8D080', fontFamily: "'Cinzel',serif" }}>{sc.state_index_final}</span>
            <span style={{ fontSize: 9, color: 'rgba(232,208,128,0.7)' }}>/ 100 · {stateLabel}</span>
          </div>
          <button onClick={onExpand} style={{ background: 'rgba(255,255,255,0.1)', border: '1px solid rgba(255,255,255,0.2)', borderRadius: 4, padding: '4px 6px', cursor: 'pointer', color: 'rgba(255,255,255,0.8)', display: 'flex', alignItems: 'center' }}>
            <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="15 3 21 3 21 9" /><polyline points="9 21 3 21 3 15" /><line x1="21" y1="3" x2="14" y2="10" /><line x1="3" y1="21" x2="10" y2="14" /></svg>
          </button>
        </div>
      </div>

      {/* Onglets */}
      <div style={{ display: 'flex', borderBottom: `1px solid ${BDR_G}`, background: BG_P }}>
        {TABS.map(tb => (
          <button key={tb.key} onClick={() => setTab(tb.key)} style={{ flex: 1, padding: '8px 4px', fontSize: 11, color: tab === tb.key ? NAVY : TXT3, background: 'none', border: 'none', borderBottom: tab === tb.key ? `2px solid ${GOLD}` : '2px solid transparent', fontFamily: "'Cinzel',serif", letterSpacing: '.06em', cursor: 'pointer' }}>
            {tb.label}
          </button>
        ))}
      </div>

      {/* Contenu */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '10px 14px' }}>

        {/* ── SITUATION : SOUMISE → LECTURE → VULNÉRABILITÉ → ASYMÉTRIE → sep → ASTROLABE ── */}
        {tab === 'situation' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {submitted && (
              <div style={{ background: 'rgba(26,42,107,0.04)', border: `1px solid ${BDR}`, borderRadius: 6, padding: '7px 10px' }}>
                <div style={{ fontSize: 8, color: TXT3, letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 3 }}>{t.situation_soumise}</div>
                <div style={{ fontSize: 11, color: TXT2, fontStyle: 'italic', fontFamily: "'Cormorant Garamond',serif", lineHeight: 1.6 }}>{submitted}</div>
              </div>
            )}
            <div style={{ background: 'rgba(184,154,106,0.08)', border: `1px solid ${BDR_G}`, borderRadius: 6, padding: '8px 10px' }}>
              <div style={{ fontSize: 8, color: GOLD, letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 4 }}>{t.lecture_label}</div>
              <div style={{ fontSize: 12, color: TXT, fontStyle: 'italic', fontFamily: "'Cormorant Garamond',serif", lineHeight: 1.6 }}>{insight}</div>
            </div>
            <div style={{ background: 'rgba(224,107,74,0.06)', border: '1px solid rgba(224,107,74,0.22)', borderRadius: 6, padding: '6px 10px' }}>
              <div style={{ fontSize: 8, color: '#E06B4A', letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 3 }}>{t.vulnerability_label}</div>
              <div style={{ fontSize: 11, color: TXT, fontWeight: 500, lineHeight: 1.5 }}>{vulnerability}</div>
            </div>
            {asymmetry && (
              <div style={{ background: 'rgba(55,138,221,0.05)', border: '1px solid rgba(55,138,221,0.18)', borderRadius: 6, padding: '6px 10px' }}>
                <div style={{ fontSize: 8, color: '#378ADD', letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 3 }}>{t.asymmetry_label}</div>
                <div style={{ fontSize: 11, color: TXT, fontStyle: 'italic', lineHeight: 1.5 }}>{asymmetry}</div>
              </div>
            )}
            <div style={{ height: 1, background: BDR_G, margin: '4px 0' }} />
            {sc.astrolabe_scores?.length > 0 && (
              <div>
                <div style={{ fontSize: 8, color: GOLD, letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 6, textAlign: 'center' }}>ASTROLABE</div>
                <div style={{ display: 'flex', justifyContent: 'center', marginBottom: 10 }}>
                  <AstrolabeRadial scores={sc.astrolabe_scores} />
                </div>
                <div style={{ fontSize: 8, color: GOLD, letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 6 }}>FORCE LINES</div>
                <ForceLines scores={sc.astrolabe_scores} lang={lang} />
              </div>
            )}
          </div>
        )}

        {/* ── CAP ── */}
        {tab === 'cap' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {hook && (
              <div style={{ background: `linear-gradient(135deg,${NAVY}08,${GOLD}08)`, border: `1px solid ${BDR_G}`, borderRadius: 6, padding: '8px 10px' }}>
                <div style={{ fontSize: 8, color: GOLD, letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 4 }}>ANCHOR</div>
                <div style={{ fontSize: 14, color: TXT, fontFamily: "'Cormorant Garamond',serif", lineHeight: 1.5, fontWeight: 500 }}>{hook}</div>
                {capInsight && <div style={{ fontSize: 11, color: TXT2, marginTop: 6, lineHeight: 1.5 }}>{capInsight}</div>}
              </div>
            )}
            {watch && (
              <div style={{ background: 'rgba(234,179,8,0.06)', border: '1px solid rgba(234,179,8,0.25)', borderRadius: 6, padding: '6px 10px' }}>
                <div style={{ fontSize: 8, color: '#A16207', letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 3 }}>WATCH</div>
                <div style={{ fontSize: 11, color: TXT, fontStyle: 'italic', lineHeight: 1.5 }}>{watch}</div>
              </div>
            )}
            {trajectories.length > 0 && (
              <div>
                <div style={{ fontSize: 8, color: GOLD, letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 6 }}>{lang === 'FR' ? 'TRAJECTOIRES' : 'TRAJECTORIES'}</div>
                {trajectories.map((tr: any, i: number) => {
                  const trType = tr.type ?? ''
                  const TRAJ_COLORS: Record<string, string> = { stabilization: '#1D9E75', escalation: '#E06B4A', regime_shift: '#378ADD' }
                  const trColor: string = tr.color ?? TRAJ_COLORS[trType] ?? '#9AABB8'
                  const lbl  = lang === 'FR' ? (tr.type_fr ?? tr.type ?? trType) : (tr.type_en ?? trType)
                  const ttl  = lang === 'FR' ? (tr.title_fr ?? tr.title ?? '') : (tr.title_en ?? tr.title ?? '')
                  const desc = lang === 'FR' ? (tr.description_fr ?? tr.description ?? '') : (tr.description_en ?? tr.description ?? '')
                  const sig  = lang === 'FR' ? (tr.signal_fr ?? tr.signal_precurseur ?? '') : (tr.signal_en ?? tr.signal_precurseur_en ?? tr.signal_precurseur ?? '')
                  return (
                    <div key={i} style={{ borderLeft: `3px solid ${trColor}`, background: `${trColor}08`, border: `1px solid ${trColor}30`, borderRadius: 5, padding: '6px 10px', marginBottom: 7 }}>
                      <div style={{ fontSize: 10, fontWeight: 600, color: trColor, marginBottom: 2 }}>{lbl}{ttl ? ` — ${ttl}` : ''}</div>
                      <div style={{ fontSize: 10, color: TXT2, lineHeight: 1.5, marginBottom: 3 }}>{desc}</div>
                      {sig && <div style={{ fontSize: 9, color: TXT3 }}>→ {sig}</div>}
                    </div>
                  )
                })}
              </div>
            )}
            {signal && (
              <div style={{ background: 'rgba(234,179,8,0.06)', border: '1px solid rgba(234,179,8,0.3)', borderRadius: 6, padding: '7px 10px' }}>
                <div style={{ fontSize: 8, color: '#A16207', letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 3 }}>KEY SIGNAL</div>
                <div style={{ fontSize: 11, color: TXT, lineHeight: 1.5 }}>{signal}</div>
              </div>
            )}
          </div>
        )}

        {/* ── ANALYSE ── */}
        {tab === 'analyse' && (
          <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
            <div>
              <div style={{ fontSize: 8, color: GOLD, letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 6 }}>DECISION RADAR</div>
              <div style={{ display: 'flex', alignItems: 'baseline', gap: 6, marginBottom: 8 }}>
                <span style={{ fontSize: 36, fontWeight: 700, color: TXT, fontFamily: "'Cinzel',serif", lineHeight: 1 }}>{sc.state_index_final}</span>
                <span style={{ fontSize: 12, color: TXT3 }}>/ 100 · {stateLabel}</span>
              </div>
              {avertissement && (
                <div style={{ fontSize: 11, color: TXT3, fontStyle: 'italic', lineHeight: 1.6, borderLeft: `2px solid ${GOLD}`, paddingLeft: 10, marginBottom: 4 }}>
                  ↓ {avertissement}
                </div>
              )}
            </div>
            {mouvements.length > 0 && (
              <div>
                <div style={{ fontSize: 8, color: GOLD, letterSpacing: '.1em', fontFamily: "'Cinzel',serif", marginBottom: 8 }}>{t.mouvements_label}</div>
                {mouvements.map((m: string, i: number) => (
                  <div key={i} style={{ display: 'flex', gap: 8, marginBottom: 7 }}>
                    <div style={{ width: 18, height: 18, borderRadius: '50%', background: NAVY, color: '#fff', fontSize: 9, display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0, fontFamily: "'Cinzel',serif" }}>{i + 1}</div>
                    <div style={{ fontSize: 12, color: TXT2, lineHeight: 1.5, paddingTop: 2 }}>{m}</div>
                  </div>
                ))}
              </div>
            )}
            <div style={{ borderTop: `1px solid ${BDR_G}`, paddingTop: 10, marginTop: 4 }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginBottom: 6 }}>
                <Image src="/pictos/Tracabilité.png" alt="" width={14} height={14} style={{ objectFit: 'contain' }} unoptimized />
                <div style={{ fontSize: 8, color: GOLD, letterSpacing: '.1em', fontFamily: "'Cinzel',serif" }}>{t.tracabilite}</div>
              </div>
              <div style={{ fontSize: 10, color: TXT3, lineHeight: 1.7 }}>
                <div>{t.generated_by} · {t.on_lbl} {new Date().toLocaleDateString(lang === 'FR' ? 'fr-FR' : 'en-GB', { day: '2-digit', month: 'long', year: 'numeric' })}</div>
                <div style={{ fontSize: 9, marginTop: 2, opacity: 0.7 }}>Version 1.0 · {lang === 'FR' ? 'Lecture structurelle' : 'Structural reading'}</div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Boutons bas */}
      <div style={{ borderTop: `1px solid ${BDR}`, padding: '8px 14px', display: 'flex', gap: 8 }}>
        <button style={{ flex: 1.2, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 6, background: NAVY, color: '#fff', border: 'none', borderRadius: 7, padding: '7px 8px', fontSize: 11, fontFamily: "'Cinzel',serif", letterSpacing: '.06em', cursor: 'pointer' }}>
          <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5"><path d="M4 12v8a2 2 0 002 2h12a2 2 0 002-2v-8" /><polyline points="16 6 12 2 8 6" /><line x1="12" y1="2" x2="12" y2="15" /></svg>
          {t.partager}
        </button>
        <button onClick={() => setLecturesOpen(true)} style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 5, background: NAVY, color: '#fff', border: 'none', borderRadius: 7, padding: '7px 8px', fontSize: 11, fontFamily: "'Cinzel',serif", letterSpacing: '.04em', cursor: 'pointer' }}>
          {t.lectures}
        </button>
        <button style={{ flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 5, background: 'transparent', color: TXT2, border: `1px solid ${BDR}`, borderRadius: 7, padding: '7px 8px', fontSize: 11, fontFamily: "'Cinzel',serif", letterSpacing: '.04em', cursor: 'pointer' }}>
          <div style={{ width: 14, height: 14, flexShrink: 0 }}>
            <Image src="/pictos/Tracabilité.png" alt="" width={14} height={14} style={{ objectFit: 'contain' }} unoptimized />
          </div>
          {t.collaboration}
        </button>
      </div>
    </div>
  )
}
