// ── Palette IAAA+ ─────────────────────────────────────────────────────────────
// Ne pas modifier sans validation JCA
export const NAVY   = '#1B3A6B'
export const GOLD   = '#B89A6A'
export const GOLD_L = '#CCA364'
export const BG     = '#F5F3EE'
export const BG_P   = '#FAFAF7'
export const BG_PR  = '#F7F5F0'
export const TXT    = '#1a2a3a'
export const TXT2   = '#5a6a7a'
export const TXT3   = '#9aabb8'
export const BDR    = 'rgba(26,42,58,0.1)'
export const BDR_G  = 'rgba(184,154,106,0.25)'

// ── Textes UI ─────────────────────────────────────────────────────────────────
export const TX = {
  FR: {
    hints: [
      "Un conflit d'équipe autour d'une réorganisation",
      "Une décision stratégique avec plusieurs options",
      "Une crise géopolitique en développement",
      "Mon partenaire s'est éloigné — comment aborder le sujet ?",
      "Une opportunité s'ouvre mais le timing semble mauvais",
    ],
    describe: 'Décrivez votre situation en texte libre.',
    analysing: 'Analyse en cours...',
    waiting: 'La SC apparaîtra ici',
    flash_title: 'Flash Update',
    flash_sc_btn: 'Situation Card complète',
    clarify_intro: 'Pour analyser votre situation :',
    clarify_btn: 'Analyser',
    tab_situation: 'Situation',
    tab_cap: 'Cap',
    tab_analyse: 'Analyse',
    partager: 'Partager',
    lectures: 'Lectures',
    collaboration: 'Collaboration',
    restreint: 'Restreint',
    public_lbl: 'Public',
    historique: 'Historique',
    saved: 'Enregistrées',
    tagline: 'Voir la structure pour pouvoir décider',
    signature: 'Que se passe-t-il vraiment ?',
    offres: 'Offres',
    connexion: 'Connexion',
    structural_reading: 'Lecture structurelle — pas une mise à jour en temps réel',
    no_saved: 'Aucune carte enregistrée.',
    generated_by: 'Généré par IAAA+ SIS',
    on_lbl: 'le',
  },
  EN: {
    hints: [
      "A team conflict around a restructuring",
      "A strategic decision with multiple options",
      "A developing geopolitical crisis",
      "My partner has grown distant — how to approach it?",
      "An opportunity is opening but the timing seems wrong",
    ],
    describe: 'Describe your situation in free text.',
    analysing: 'Analysing...',
    waiting: 'The SC will appear here',
    flash_title: 'Flash Update',
    flash_sc_btn: 'Full Situation Card',
    clarify_intro: 'To analyse your situation:',
    clarify_btn: 'Analyse',
    tab_situation: 'Situation',
    tab_cap: 'Cap',
    tab_analyse: 'Analysis',
    partager: 'Share',
    lectures: 'Readings',
    collaboration: 'Collaborate',
    restreint: 'Private',
    public_lbl: 'Public',
    historique: 'History',
    saved: 'Saved',
    tagline: 'See the structure to decide',
    signature: 'What is really happening?',
    offres: 'Plans',
    connexion: 'Sign in',
    structural_reading: 'Structural reading — not a real-time update',
    no_saved: 'No saved cards yet.',
    generated_by: 'Generated by IAAA+ SIS',
    on_lbl: 'on',
  },
} as const

export type Lang = 'FR' | 'EN'

// ── Mapping branches ──────────────────────────────────────────────────────────
export const BRANCH_FR: Record<string, string> = {
  I:'Acteurs', II:'Intérêts', III:'Forces', IV:'Tensions',
  V:'Contraintes', VI:'Incertitude', VII:'Temps', VIII:'Espace',
}
export const BRANCH_EN: Record<string, string> = {
  I:'Actors', II:'Interests', III:'Forces', IV:'Tensions',
  V:'Constraints', VI:'Uncertainty', VII:'Time', VIII:'Space',
}

// ── Trajectory colors — du type au hex ───────────────────────────────────────
export const TRAJECTORY_COLORS: Record<string, string> = {
  stabilization: '#1D9E75',
  escalation:    '#E06B4A',
  regime_shift:  '#378ADD',
  // legacy (ancien format)
  'Stabilisation': '#1D9E75',
  'Escalade':      '#E06B4A',
  'Rupture':       '#378ADD',
}

// ── State label ───────────────────────────────────────────────────────────────
export function getStateLabel(state: number, lang: Lang = 'FR'): string {
  if (lang === 'EN') {
    if (state < 40) return 'Clear'
    if (state < 55) return 'Navigable'
    if (state < 70) return 'Watch'
    if (state < 90) return 'Critical'
    return 'Loss of Control'
  }
  if (state < 40) return 'Stable'
  if (state < 55) return 'Contrôlable'
  if (state < 70) return 'Vigilance'
  if (state < 90) return 'Critique'
  return 'Hors contrôle'
}
